name: Badge

on:
  push:
    branches:
      - main

jobs:
  badge:
    name: Code Coverage Badge
    runs-on: ubuntu-latest
    steps:
      - name: Download Code Coverage Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
          workflow: ci.yml
          if_no_artifact_found: warn
      - name: Check Code Coverage Report
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: coverage/coverage-summary.json
      - name: Create Code Coverage Badge
        if: steps.check_files.outputs.files_exists == 'true'
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: coverage/coverage-badge.svg
          label: Coverage
      - name: Upload Code Coverage Badge
        if: steps.check_files.outputs.files_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage
