name: CI

on: [pull_request]

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=3 & yarn nx affected --target=test --parallel=3 --ci --code-coverage & yarn nx affected --target=build --parallel=3
      artifacts-name: code-coverage-report
      artifacts-path: coverage/nx-angular-barbershop

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3

  badge:
    name: Code Coverage Badge
    runs-on: ubuntu-latest
    needs: main
    continue-on-error: true
    steps:
      - name: Download Code Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
      - name: Check Code Coverage Report
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: coverage/coverage-summary.json
      - name: Create Code Coverage Badge
        if: steps.check_files.outputs.files_exists == 'true'
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: coverage/coverage-badge.svg
          label: Coverage
      - name: Upload Code Coverage Badge
        if: steps.check_files.outputs.files_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage
